name: Quotes Generator Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Generate repository
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone https://github.com/Codenuclei/Quotes-Generator.git
        cp -R ./* Quotes-Generator/
        cd Quotes-Generator
        git add .
        git commit -m "Update repository"
        git push

    - name: Deploy to repository
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: Quotes-Generator
